#:schema node_modules/wrangler/config-schema.json
name = "botsinbox-tokens"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./static/" }

[observability]
enabled = true

[env.production.vars]
INSTANCE = "https://botsinbox.net"

[[env.production.routes]]
pattern = "token.botsinbox.net"
custom_domain = true

[[env.production.kv_namespaces]]
binding = "KV"
id = "9c3e8eecf00f46f0a5fd7772866e6f15"
